"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => General
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Font
set anti enc=utf-8
set guifont=Sauce\ Code\ Powerline\ Semibold:h14

# Transparency
set transp=2
