"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => General
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Font
set anti enc=utf-8
set guifont=Source\ Code\ Pro\ Semibold:h14

# Transparency
set transp=2
