ZSH=$HOME/.oh-my-zsh
# Path to your oh-my-zsh configuration.

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Default User
DEFAULT_USER="Gerardo"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)

DISABLE_UPDATE_PROMPT=true

plugins=(osx git git-extras vagrant brew node npm python cp docker docker-compose gitignore zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
# Aliases
alias dotfiles="cd ~/.dotfiles"
alias dotfiles_update='ORIGINAL_PATH=${PWD} && cd ~/.dotfiles && git stash && git pull origin master && git stash apply stash@{0} > /dev/null && cd ${ORIGINAL_PATH}'
alias vi="vim"
alias vimrc="vim ~/.vimrc"
alias zshrc="vim ~/.zshrc"
alias projects="cd ~/Projects"
alias myip="curl ifconfig.co 2> /dev/null || echo 0.0.0.0"
alias reload="source ~/.zshrc"
alias screensaver="open -a /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app"

# Enable Colors
export CLICOLOR=1;
export LSCOLORS=exfxcxdxbxegedabagacad;

export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH
export EDITOR="/usr/local/bin/vim"
export PAGER="/usr/local/bin/most"
export GIT_PAGER="/usr/bin/less"

# Locale
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Bind Keys
bindkey -e
bindkey '^[[1;9C' forward-word
bindkey '^[[1;9D' backward-word

fpath=($HOME/.zsh/func $fpath)
typeset -U fpath

source /usr/local/etc/grc.bashrc.default

if [[ -x `which grc` ]]; then
    alias grc='grc --colour=auto'
fi
